image: thlmylab/swakkd:1.23

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

pypi:
    stage: deploy
    script:
        - apk add build-base libffi-dev python-dev
        - pip install twine
        - python setup.py sdist
        - twine upload dist/*
