image: thlmylab/swakkd:1.23

stages:
  - build
  - test
  - deploy

pypi:
    stage: deploy
    script:
        - apk add build-base libffi-dev
        - pip install twine
        - python setup.py sdist
        - twine upload dist/*
